# authentication error messages
authentication.err.validation.authenticator.notfound=Tunnistautuminen ep\u00e4onnistui, tarkistetta nimell\u00e4 {0} ei l\u00f6ytynyt 
authentication.err.validation.authenticator.notactive=Tarkiste ei ole aktiivinen

authentication.err.authentication=Tunnistautuminen ep\u00e4onnistui, k\u00e4ytt\u00e4j\u00e4nimi tai salasana on v\u00e4\u00e4rin. K\u00e4ytt\u00e4j\u00e4nimi:{0} Syy {1}
authentication.err.connection=Ei onnistuttu yhdist\u00e4m\u00e4\u00e4n kohteeseen {0}. Syy {1}
authentication.err.communication=Yhteydenpito kohteeseen {0} ep\u00e4onnistui. Syy {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Ei onnistuttu yhdist\u00e4m\u00e4\u00e4n, ldap is\u00e4nt\u00e4 {0} on tuntematon
authentication.err.connection.ldap.user.notfound=LDAP k\u00e4ytt\u00e4j\u00e4\u00e4 {0} ei l\u00f6ytynyt
authentication.err.connection.ldap.manager.notfound=LDAP johtaja-tason k\u00e4ytt\u00e4j\u00e4\u00e4 {0} ei l\u00f6ytynyt
authentication.err.connection.ldap.search=Ei voitu etsi\u00e4 LDAP:ia. Syy {0}

# PASSTHRU
authentication.err.connection.passthru.server=Ei onnistuttu avaamaan istuntoa passthru -palvelimelle
authentication.err.passthru.token.unsupported=Ei-tuettu tunnistautumistunnuksen tyyppi
authentication.err.passthru.guest.notenabled=Vieraskirjautumiset ovat pois k\u00e4yt\u00f6st\u00e4
authentication.err.passthru.user.disabled=Tili ei ole k\u00e4yt\u00f6ss\u00e4
authentication.err.passthru.user.notfound=Passthru -k\u00e4ytt\u00e4j\u00e4\u00e4 {0} ei l\u00f6ytynyt

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Pyynn\u00f6n vahvistaminen
authentication.step.ldap.connecting=Yhdist\u00e4\u00e4 LDAP -palvelimelle {0} 
authentication.step.ldap.connected=Yhteydess\u00e4 LDAP -palvelimeen {0} with principal: {1}
authentication.step.ldap.lookup=Hae Testi K\u00e4ytt\u00e4j\u00e4 k\u00e4ytt\u00e4j\u00e4tunnus:{0} kyselyll\u00e4: {1}
authentication.step.ldap.lookedup=Haettiin Testi K\u00e4ytt\u00e4j\u00e4 k\u00e4ytt\u00e4j\u00e4tunnus:{0}, l\u00f6ydettiin luokiteltu nimi (DN):{1}
authentication.step.ldap.format.user=K\u00e4ytt\u00e4j\u00e4nimen esitysmuoto m\u00e4\u00e4ritelty, K\u00e4ytt\u00e4j\u00e4nimen esitysmuoto:{2} Formatoi k\u00e4ytt\u00e4j\u00e4tunnus:{0} tehd\u00e4ksesi luokitellun nimen (DN):{1}
authentication.step.ldap.authentication=Varmenna k\u00e4ytt\u00e4j\u00e4tunnus:{0}


# Sync Summary message 
synchronization.summary.status={0} k\u00e4ytt\u00e4j\u00e4(\u00e4) ja {1} ryhm\u00e4(\u00e4) k\u00e4sitelty


# Error messages
authentication.ldap.validation.authenticator.notfound=Tarkistetta ei l\u00f6ytynyt

# Synchronization Diagnostic Steps
synchronization.step.users=L\u00f6ydettiin {0} k\u00e4ytt\u00e4j\u00e4(\u00e4)
synchronization.step.groups=L\u00f6ydettiin {0} ryhm\u00e4(\u00e4)
synchronization.step.users.lastsynced={0} k\u00e4ytt\u00e4j\u00e4\u00e4 synkronoitu onnistuneesti
synchronization.step.groups.lastsynced={0} ryhm\u00e4\u00e4 synkronoitu onnistuneesti

synchronization.err.ldap.search=Virhe LDAP haun aikana. Syy:{0}
synchronization.err.ldap.get.user.id.missing=K\u00e4ytt\u00e4j\u00e4lt\u00e4 puuttuu k\u00e4ytt\u00e4j\u00e4tunnuksen attribuutti DN = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Ryhm\u00e4lt\u00e4 puuttuu ryhm\u00e4tunnuksen attribuutti = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Virheellinen hakukanta {0} syy: {1}

synchronization.err.ldap.group.member.missing.exception="Ryhm\u00e4n j\u00e4senen {0} selvitt\u00e4minen luokitellulla nimell\u00e4: {1} ep\u00e4onnistui, syy {2});
synchronization.err.ldap.group.member.missing="Ryhm\u00e4n j\u00e4senen {0} selvitt\u00e4minen luokitellulla nimell\u00e4: {1} ep\u00e4onnistui);



       



